[20306] Add an auto fill type information check
eProsima/ShapesDemo pull request #107
Opened 2024-01-24 15:30 UTC by EduPonz

This PR adds a check button to avoid sending type information during discovery. Related PRs:
- Fast DDS: eProsima/Fast-DDS#4291
- Shapes Demo Documentation: eProsima/Shapes-Demo-Docs#89

2024-01-24 15:35 UTC, MiguelCompany requested changes

2024-01-24 15:35 UTC, MiguelCompany commented on src/shapesdemo/ShapesDemo.cpp
> +        m_type->auto_fill_type_information(false);
```suggestion
        m_type->auto_fill_type_information(m_options.m_auto_fill_type_information);
```

2024-01-25 08:14 UTC, MiguelCompany approved these changes

2024-01-25 13:35 UTC, EduPonz commented
@mergifyio backport 2.6.x 2.10.x 2.11.x 2.12.x

2024-01-26 06:55 UTC, merged