[21229] Improve CI workflows in master
eProsima/ShapesDemo pull request #150
Opened 2024-06-27 09:56 UTC by JesusPoderoso

## Description

This PR improves the GitHub CI of this repo, to make it as similar as the one in Fast DDS

**Note**: While backporting this PR, please ensure the following changes:
- Remove nightly jobs
- Update `ubuntu-ci.yml` and `windows-ci.yml` files with the proper fallback branches
- Change `fastdds.repos` to `fastrtps.repos`
- 2.x branches require both `v141` and `v142` vs toolsets
- 2.6.x requires building on `ubuntu-20.04`

For those reasons, a **manual backport to 2.14.x** will be opened, and that one will be backported to remain branches.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- **N/A** Changes do not break current interoperability.
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

2024-06-27 15:00 UTC, elianalf requested changes

2024-06-27 15:00 UTC, elianalf commented on .github/workflows/reusable-windows-ci.yml
> +  shapes_demo_build:
```suggestion
  reusable-windows-ci:
```

2024-06-27 15:00 UTC, elianalf commented on .github/workflows/reusable-ubuntu-ci.yml
> +  shapes_demo_build:
```suggestion
  reusable-ubuntu-ci:
```

2024-06-27 15:00 UTC, elianalf commented on .github/workflows/ubuntu-ci.yml
> +
```suggestion
```

2024-06-27 15:00 UTC, elianalf commented on .github/workflows/ubuntu-ci.yml
> +  ubuntu-ci:
I think that this check can be moved here, so when a PR has conflicts we can see the jobs skipped
```suggestion
  ubuntu-ci:
        if: ${{ (
              !contains(github.event.pull_request.labels.*.name, 'conflicts')
            ) }}
```

2024-06-27 15:00 UTC, elianalf commented on .github/workflows/reusable-windows-ci.yml
> +  shapes_demo_build:
```suggestion
  reusable-windows-ci:
```

2024-06-27 15:00 UTC, elianalf commented on .github/workflows/reusable-ubuntu-ci.yml
> +  shapes_demo_build:
```suggestion
  reusable-ubuntu-ci:
```

2024-06-28 10:17 UTC, JesusPoderoso commented on .github/workflows/nightly-windows-ci.yml
> +      run-build: false
🤦 ups

2024-06-28 10:24 UTC, JesusPoderoso commented on .github/workflows/reusable-windows-ci.yml
> +        description: 'Build Fast DDS Python (CI skipped otherwise)'
🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦v

2024-07-01 14:09 UTC, merged

2024-07-01 14:10 UTC, JesusPoderoso commented
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x