[18328] TCP ComboBox saving the user selected option
eProsima/ShapesDemo pull request #78
Opened 2023-06-01 06:22 UTC by Mario-DL

In the Participant configuration dialog, when the user selects an option different from `TCP LAN Server`, starts the participant and closes the dialog, the ComboBox does not save the selected option, hence, when re-opening the dialog again, it is always showed the default `TCP LAN Server`.
This little PR fixes it.

2023-06-01 07:43 UTC, JesusPoderoso reviewed
A little nitpick: the labels are not disabled with the selected options, we can easily fix that too by renaming the `label_6`, `label_7` and `label_8` as `serverIP_label`, `serverPort_label`, and `listeningPort_label`, respectively (in the UI file), and including them in the following case:

```
void ParticipantDialog::tcp_enable_buttons()
{
    // Enable Combo Box
    this->ui->TCPcomboBox->setEnabled(m_options->m_tcp_transport && mb_started);

    // Enable/Disable buttons depending on transport
    this->ui->spin_listen_port->setEnabled(m_options->m_tcp_transport && mb_started);
    this->ui->spin_server_port->setEnabled(m_options->m_tcp_transport && mb_started);
    this->ui->lineEdit_server_ip->setEnabled(m_options->m_tcp_transport && mb_started);

    // Enable/Disable labels depending on transport
    this->ui->listeningPort_label->setEnabled(m_options->m_tcp_transport && mb_started);
    this->ui->serverPort_label->setEnabled(m_options->m_tcp_transport && mb_started);
    this->ui->serverIP_label->setEnabled(m_options->m_tcp_transport && mb_started);

    if (QString("TCP LAN Server") == m_options->m_tcp_type)
    {
        this->ui->spin_server_port->setEnabled(false);
        this->ui->lineEdit_server_ip->setEnabled(false);
        this->ui->serverIP_label->setEnabled(false);
        this->ui->serverPort_label->setEnabled(false);
    }
    if (QString("TCP WAN Server") == m_options->m_tcp_type)
    {
        this->ui->spin_server_port->setEnabled(false);
        this->ui->serverPort_label->setEnabled(false);
    }
    if (QString("TCP Client") == m_options->m_tcp_type)
    {
        this->ui->spin_listen_port->setEnabled(false);
        this->ui->listeningPort_label->setEnabled(false);
    }

    this->ui->TCPcomboBox->setCurrentText(m_options->m_tcp_type);
}
```

2023-06-01 07:44 UTC, JesusPoderoso approved these changes
LGTM

2023-06-01 14:39 UTC, Mario-DL commented
> Suggestion: the labels are not disabled with the selected options, we can easily fix that too by renaming the `label_6`, `label_7` and `label_8` as `serverIP_label`, `serverPort_label`, and `listeningPort_label`, respectively (in the UI file), and including them in the following case:
> 
> ```
> void ParticipantDialog::tcp_enable_buttons()
> {
>     // Enable Combo Box
>     this->ui->TCPcomboBox->setEnabled(m_options->m_tcp_transport && mb_started);
> 
>     // Enable/Disable buttons depending on transport
>     this->ui->spin_listen_port->setEnabled(m_options->m_tcp_transport && mb_started);
>     this->ui->spin_server_port->setEnabled(m_options->m_tcp_transport && mb_started);
>     this->ui->lineEdit_server_ip->setEnabled(m_options->m_tcp_transport && mb_started);
> 
>     // Enable/Disable labels depending on transport
>     this->ui->listeningPort_label->setEnabled(m_options->m_tcp_transport && mb_started);
>     this->ui->serverPort_label->setEnabled(m_options->m_tcp_transport && mb_started);
>     this->ui->serverIP_label->setEnabled(m_options->m_tcp_transport && mb_started);
> 
>     if (QString("TCP LAN Server") == m_options->m_tcp_type)
>     {
>         this->ui->spin_server_port->setEnabled(false);
>         this->ui->lineEdit_server_ip->setEnabled(false);
>         this->ui->serverIP_label->setEnabled(false);
>         this->ui->serverPort_label->setEnabled(false);
>     }
>     if (QString("TCP WAN Server") == m_options->m_tcp_type)
>     {
>         this->ui->spin_server_port->setEnabled(false);
>         this->ui->serverPort_label->setEnabled(false);
>     }
>     if (QString("TCP Client") == m_options->m_tcp_type)
>     {
>         this->ui->spin_listen_port->setEnabled(false);
>         this->ui->listeningPort_label->setEnabled(false);
>     }
> 
>     this->ui->TCPcomboBox->setCurrentText(m_options->m_tcp_type);
> }
> ```

I think it is a nice suggestion ! Including it

2023-06-01 14:50 UTC, JesusPoderoso requested changes
Little nitpick: You changed the name in other non-related widgets

2023-06-01 14:50 UTC, JesusPoderoso commented on forms/publishdialog.ui
> -    <widget class="QLabel" name="label_8">
Should not have been changed in this document

2023-06-01 14:50 UTC, JesusPoderoso commented on forms/subscribedialog.ui
> +   <widget class="QLabel" name="serverIP_label">
Should not have been changed in this document neither

2023-06-01 14:50 UTC, JesusPoderoso commented on forms/ui/ui_publishdialog.h
> -    QLabel* label_6; //History
Should not have been changed in this document neither

2023-06-01 14:50 UTC, JesusPoderoso commented on forms/ui/ui_subscribedialog.h
> +    QLabel *serverPort_label; //Size
Should not have been changed in this document neither

2023-06-02 06:47 UTC, JesusPoderoso approved these changes
LGTM

2023-06-02 06:49 UTC, merged